// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2018;

import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import com.ctre.phoenix.motorcontrol.can.VictorSPX;
import com.kauailabs.navx.frc.AHRS;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.SerialPort;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.hal.PDPJNI;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	//MAking the speedController, sensors, and pneumatic objects
    public static TalonSRX driveTrainLeftBack;
    public static TalonSRX driveTrainLeftFront;
    public static TalonSRX driveTrainRightFront;
    public static TalonSRX driveTrainRightBack;
    public static VictorSPX spinIntake1;
    public static VictorSPX spinIntake2;
    public static VictorSPX swingIntake1;
    public static Talon swingIntake2;
    public static VictorSP insideIntake1;
    public static VictorSP insideIntake2;
    public static Ultrasonic sensorsUltrasonicSensor;
    public static DoubleSolenoid pneumaticsDoubleSolenoid1;
    public static DoubleSolenoid pneumaticsDoubleSolenoid2;
    public static Compressor pneumaticsCompressor1;
    public static Spark ElevatorSpark1; 
    public static Spark ElevatorSpark2;  
    public static DigitalInput sensorsLimitSwitch1;
//    public static DigitalInput sensorsLimitSwitch2; 
    public static AHRS gyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	//the actuators are given the talonSRX 
        
    	driveTrainLeftBack = new TalonSRX(4);
        
        driveTrainLeftFront = new TalonSRX(3);
        
        driveTrainRightFront = new TalonSRX(2);
        
        driveTrainRightBack = new TalonSRX(1);
        
        sensorsUltrasonicSensor = new Ultrasonic(1, 2);
        LiveWindow.add(sensorsUltrasonicSensor);
        
        pneumaticsDoubleSolenoid1 = new DoubleSolenoid(1, 4, 5);
        LiveWindow.add(pneumaticsDoubleSolenoid1);
        
        pneumaticsDoubleSolenoid2 = new DoubleSolenoid(1, 6, 7);
        LiveWindow.add(pneumaticsDoubleSolenoid2);
        
        
        pneumaticsCompressor1 = new Compressor(1);
        //giving sparks which one it is
        ElevatorSpark1 = new Spark(4); 
        LiveWindow.add(ElevatorSpark1); 
        
        ElevatorSpark2 = new Spark(5); 
        LiveWindow.add(ElevatorSpark2);
        
        sensorsLimitSwitch1 = new DigitalInput(0); 
        LiveWindow.add(sensorsLimitSwitch1); 
//        
//        sensorsLimitSwitch2 = new DigitalInput(1); 
//        LiveWindow.add(sensorsLimitSwitch2); 

        swingIntake1 = new VictorSPX(3);
        
        swingIntake2 = new Talon(6);
        
        spinIntake1 = new VictorSPX(1);
        
        spinIntake2 = new VictorSPX(2);
        
        insideIntake1 = new VictorSP(3);//no
        
        insideIntake2 = new VictorSP(2);
       
        gyro = new AHRS(SPI.Port.kMXP);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
