// Cazathia and Justin
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2018.subsystems;

import org.usfirst.frc253.Code2018.RobotMap;
import org.usfirst.frc253.Code2018.commands.*;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftBack = RobotMap.driveTrainLeftBack;
    private final SpeedController leftFront = RobotMap.driveTrainLeftFront;
    private final SpeedController  leftCenter = RobotMap.driveTrainLeftCenter;
    private final SpeedController rightFront = RobotMap.driveTrainRightFront;
    private final SpeedController rightBack = RobotMap.driveTrainRightBack;
    private final SpeedController rightCenter = RobotMap.driveTrainRightCenter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new tankDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void drive(double leftspeed, double rightspeed){
    	leftFront.set(leftspeed * -1);// We are setting the speed controllers to speed
    	leftBack.set(leftspeed * -1);//the leftfront and back are multiplied by -1 because the values are reversed 
    	leftCenter.set(leftspeed * -1);
    	rightFront.set(rightspeed);
    	rightBack.set(rightspeed);
    	rightCenter.set(rightspeed);
    }
}

