// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

//Audrey and Kristen :)

package org.usfirst.frc253.Code2018.subsystems;

import org.usfirst.frc253.Code2018.Robot;
import org.usfirst.frc253.Code2018.RobotMap;
import org.usfirst.frc253.Code2018.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Elevator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
	private final Spark ElevatorSpark1 = RobotMap.ElevatorSpark1;
	private final Spark ElevatorSpark2 = RobotMap.ElevatorSpark2;
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	setDefaultCommand(new ElevatorLift());
    } 

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    
    
    public Elevator(){
    	
    }
    //values for the sparks that control the elevator and sweeps
    public void move(double speed){
    	
    	ElevatorSpark2.set(speed);
    	ElevatorSpark1.set(speed);
    }
    public void lift(){
    	ElevatorSpark2.set(.6);
    	ElevatorSpark1.set(.6);
    }
    public void lower(){
    	ElevatorSpark2.set(-.1);
    	ElevatorSpark1.set(-.1);
    }
    public void eleStop(){
    	ElevatorSpark2.set(.225);
    	ElevatorSpark1.set(.225);	
    }
    public void pidControl(double output){
    	ElevatorSpark2.pidWrite(output * 0.8);
    	ElevatorSpark1.pidWrite(output);
    }
}


