// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
// 

package org.usfirst.frc253.Code2018.subsystems;

import org.usfirst.frc253.Code2018.RobotMap;
import org.usfirst.frc253.Code2018.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


//Sabien wa baka desu :> and Ryan-oniiiiichannnnn~ 
/**
 *
 */
public class Pneumatics extends Subsystem {

	//getting the solenoid objects from robotMap
    private final DoubleSolenoid solenoidShift = RobotMap.pneumaticsDoubleSolenoid1;
    private final DoubleSolenoid solenoid2 = RobotMap.pneumaticsDoubleSolenoid2;
    private final Compressor compressor1 = RobotMap.pneumaticsCompressor1;

    
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {

        // Set the default command for subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new gearShift());
    	//setting gearShift as the default command for pneumatics
    }
    //giving the solenoids and compressor value
    public void compressStart(){
    	compressor1.setClosedLoopControl(true);
    }//we turned on compressor
    public void compressStop(){
    	compressor1.setClosedLoopControl(false);
    }//This turns the compressor off
    public void doubleSolenoid1Forward(){
    	solenoidShift.set(DoubleSolenoid.Value.kForward);
    }//Makes solenoid push out
    public void doubleSolenoid1Reverse(){
    	solenoidShift.set(DoubleSolenoid.Value.kReverse);
    }//makes solenoid retract
    public void doubleSolenoid1Off(){
    	solenoidShift.set(DoubleSolenoid.Value.kOff);
    }//turns off solenoid

}