// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
// 

package org.usfirst.frc253.Code2018.subsystems;

import org.usfirst.frc253.Code2018.RobotMap;
import org.usfirst.frc253.Code2018.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


//Sabien wa baka desu :> and Ryan-oniiiiichannnnn~ 
/**
 *
 */
public class Pneumatics extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid doubleSolenoid1 = RobotMap.pneumaticsDoubleSolenoid1;
    private final DoubleSolenoid doubleSolenoid2 = RobotMap.pneumaticsDoubleSolenoid2;
    private final DoubleSolenoid doubleSolenoid3 = RobotMap.pneumaticsDoubleSolenoid3;
    private final Compressor compressor1 = RobotMap.pneumaticsCompressor1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	
    }
    public void compressStart(){
    	compressor1.setClosedLoopControl(true);
    }//we turned on compressor
    public void compressStop(){
    	compressor1.setClosedLoopControl(false);
    }//This turns the compressor off
    public void doubleSolenoid1Forward(){
    	doubleSolenoid1.set(DoubleSolenoid.Value.kForward);
    }//Makes solenoid push out
    public void doubleSolenoid1Reverse(){
    	doubleSolenoid1.set(DoubleSolenoid.Value.kReverse);
    }//makes solenoid retract
    public void doubleSolenoid1Off(){
    	doubleSolenoid1.set(DoubleSolenoid.Value.kOff);
    }//turns off solenoid
    public void doubleSolenoid2Forward(){
    	doubleSolenoid2.set(DoubleSolenoid.Value.kForward);
    }
    public void doubleSolenoid2Reverse(){
    	doubleSolenoid2.set(DoubleSolenoid.Value.kReverse);
    }
    public void doubleSolenoid2Off(){
    	doubleSolenoid2.set(DoubleSolenoid.Value.kOff);
    }
    public void doubleSolenoid3Forward(){
    	doubleSolenoid3.set(DoubleSolenoid.Value.kForward);
    }
    public void doubleSolenoid3Reverse(){
    	doubleSolenoid3.set(DoubleSolenoid.Value.kReverse);
    }
    public void doubleSolenoid3Off(){
    	doubleSolenoid3.set(DoubleSolenoid.Value.kOff);
    }
}