// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

//Audrey and Kristen :)

package org.usfirst.frc253.Code2018.subsystems;

import org.usfirst.frc253.Code2018.RobotMap;
import org.usfirst.frc253.Code2018.commands.*;

import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Sensors extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Ultrasonic ultrasonicSensor = RobotMap.sensorsUltrasonicSensor;
    private final DigitalInput limitswitch1 = RobotMap.sensorsLimitSwitch1; 
//    private final DigitalInput limitswitch2 = RobotMap.sensorsLimitSwitch2; 
//    private final AHRS gyro = RobotMap.gyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	setDefaultCommand(new ReadData());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public Sensors(){
    	ultrasonicSensor.setAutomaticMode(true);
    	// Actviates ultrasonicSensor 
//    	gyro.enableLogging(true);
    }
    public double getDistance(){ 
    	return ultrasonicSensor.getRangeInches(); 
    	// Tells how far it is from object
    }
    public DigitalInput getLimitSwitch1(){
    	return limitswitch1; 
    	//Construction needs to tell us bruh
    }
//    public boolean getLimitSwitch2(){
//    	return limitswitch2.get(); 
//    	//We don't know yet 
//    }
//    public double getYaw(){
//    	return gyro.getYaw();
//    }
//    
//    public double getPitch(){
//    	return gyro.getPitch();
//    }
//    
//    public double getRoll(){
//    	return gyro.getRoll();
//    }
}


